project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Ansoumana Bodian"
  description: Ansoumana Bodian, Hydrologue, Enseignat-Chercheur à l'université Gastion berget de Saint-Louis.
  favicon: img/logo.jpg
  search: 
    location: navbar
    type: overlay
    copy-button: true

  page-footer:
    left: "&copy; Copyright 2023, Ansoumana BODIAN"
    right: "This page is built with [GitHub](https://github.com/) and [Quarto](https://quarto.org/)."

  navbar:
    # logo: img/bodian_profile.jpg
    search: true
    # pinned: true
    left:
      # - text: "Accueil"
      #   file: index.qmd
      - text: Supervisions Académiques
        file: supervisions/index.qmd
      - text: Publications
        file: publications/2023.qmd
      - text: Projets
        href: projects/2023.qmd
      # - text: "CV"
      #   file: about.qmd
      - text: Ressources
        menu: 
          - text: CSE
            href: https://www.cse.sn/
            target: _blank
          - text: DGPRE
            href: http://www.dgpre.gouv.sn/
            target: _blank
          - text: R Weekly
            href: https://rweekly.org/
            target: _blank
          - text: R Bloggers
            href: https://www.r-bloggers.com/
            target: _blank
          - text: ResearchGate
            href: https://www.researchgate.net/
            target: _blank
          - text: Google Scholar
            href: https://scholar.google.com/
            target: _blank
      
    tools:
      - icon: envelope
        menu:
          - text: ansoumana.bodian@ugb.edu.sn
            href:  mailto:ansoumana.bodian@ugb.edu.sn
            target: _blank
          - text: bodianansoumana@gmail.com
            href:  mailto:bodianansoumana@gmail.com
            target: _blank
      - icon: linkedin
        menu:
          - text: Profile
            href:  https://www.linkedin.com/in/ansoumana-bodian-62a7aa60/?originalSubdomain=sn
            target: _blank
          - text: Projets
            href:  https://www.linkedin.com/in/ansoumana-bodian-62a7aa60/details/projects/
            target: _blank
          - text: Compétences
            href: https://www.linkedin.com/in/ansoumana-bodian-62a7aa60/details/skills/
            target: _blank
          - text: Publications
            href: https://www.linkedin.com/in/ansoumana-bodian-62a7aa60/details/publications/
            target: _blank
  sidebar:
    - id: site_web
      logo: img/logo_grid.png
      collapse-level: 4
      style: "docked"
      # background: light
      contents:
        # - section: "Cours"
        #   contents: 
        #     - courses/masterOA2C/course.qmd
        - section: "Supervisions Académiques"
          contents: 
            - section: Thèses de Doctorat
              contents: 
                - supervisions/thesis/encours.qmd
                - supervisions/thesis/soutenus.qmd
            - section: Mémoires de Master
              contents: 
                - supervisions/memoires/master2.qmd
                - supervisions/memoires/master1.qmd
        - section: Publications
          contents: 
            - publications/2023.qmd
            - publications/2022.qmd
            - publications/2021.qmd
            - publications/2020.qmd
            - publications/2019.qmd
            - publications/2018.qmd
            - publications/2017.qmd
            - publications/2016.qmd
            - publications/2015.qmd
            - publications/2014.qmd
            - publications/2013.qmd
            - publications/2012.qmd
            - publications/2011.qmd
        - section: Projets
          contents: 
            - projects/2023.qmd
            - projects/2022.qmd
            - projects/2021.qmd
            - projects/2020.qmd
            - projects/2018.qmd
            - projects/2017.qmd
            - projects/2015.qmd
            - projects/2014.qmd
            - projects/2012.qmd
            - projects/2009.qmd

format:
  html:
    grid:
      sidebar-width: 285px
      margin-width: 340px
      # body-width: 800px
    theme: 
      - cosmo
      - styles.scss
    toc: true
    toc-title: Sur cette page
